### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by Shusshu**
See example here https://travis-ci.org/Shusshu/BiglyBT/builds/275623617

This will run on every PR to ensure the build compiles and run tests (We might need to do some setup or reorganise the test location to automatically run them)

### CODE REVIEW

**Comment by TuxPaper** [comment]
Lordy, do we have tests!?!?!? ;)

I'll merge this when I have a moment to link travis-ci.org to our github account.

In the past I've just relied on parg complaining the source doesn't compile after I commit something, so this might be a step up ;)

**Comment by Shusshu** [comment]
I'm sure it's still a good _local_ system ;)

**Comment by davisjackie321** [comment]
Yo

**Comment by davisjackie321** [comment]
Nice

**Comment by davisjackie321** [comment]
Go

**Comment by davisjackie321** [comment]
Nice

**Comment by yusdiana** [comment]
H

**Comment by ferdnyc** [comment]
Hey, so I couldn't help but notice that @Shusshu 's Travis CI instance for BiglyBT [is still running builds _anyway_](https://travis-ci.org/Shusshu/BiglyBT/builds). But they're all failing, since without a `.travis.yml` config file to tell it otherwise, it defaults to trying to build the project as Ruby source.

Since having that file in the tree has literally no effect except when Travis CI is running builds, there can't be any harm in merging this, right? Even if Travis isn't set up in GitHub, it just means the source will be ready for that to happen.

**Comment by parg** [comment]
Did that fix anything?

**Comment by Shusshu** [comment]
Yes but it's not building ^^  Gotta figure that out now

**Comment by Shusshu** [comment]
Yes that worked out :)

**Pull request merged**
