### PR TITLE
Feature/maven setup

### PR DESCRIPTION
**Pull request by Shusshu**
https://github.com/BiglySoftware/BiglyBT/issues/13

It's not exactly the same jar produced by the installer - the latter includes plugins that is not part of the github code base

### CODE REVIEW

**Comment by TuxPaper** [comment]
Thanks for starting this!

It would be good to get the two jars as close as possible. What exactly did you find included in the installer's biglybt.jar that's not part of the github codebase?

afaik, we just use https://github.com/BiglySoftware/BiglyBT/blob/master/core/BiglyBT_parg.jardesc to build the jar, then jarsign it.

**Comment by Shusshu** [comment]
After fixing the maven build that's what I have now:

The following packages are missing from the code base:
package com.biglybt.core.neuronal
package com.biglybt.core.speedmanager.impl.v3


And these packages are part of the build with maven but not from the installer
package com.biglybt.core.util.spi;
package com.biglybt.core.util.dns;
package com.biglybt.core.util.jman;
package com.biglybt.core.xml.util;
and many others but most of them are just empty classes

**Comment by TuxPaper** [comment]
> The following packages are missing from the code base:
> package com.biglybt.core.neuronal
> package com.biglybt.core.speedmanager.impl.v3

These have been removed since the 1.0.0.0, so everything is good there.

> And these packages are part of the build with maven but not from the installer
> package com.biglybt.core.util.spi;
> package com.biglybt.core.util.dns;
> package com.biglybt.core.util.jman;
> package com.biglybt.core.xml.util;

hmm, I'm seeing files in the release jar
image

I do know some/most of those packages you listed are invoked by reflection, but I don't think that makes a difference.

**Comment by Shusshu** [comment]
> These have been removed since the 1.0.0.0, so everything is good there.

Well it's still in the code base on github ;)

For the rest I think it's fine.

Maybe you can see for yourself the jar diff by running 
`mvn clean package`

**Comment by TuxPaper** [comment]
Definitely not on Github! https://github.com/BiglySoftware/BiglyBT/commit/2a6641f78e3dff2bae6f701983385da8addce5ee

But that's really unimportant to this, so I'll approve the pull.  Hopefully it's as easy as clicking that lovely green button, although the drop down arrow on it is suspicious ;)

**Pull request merged**
