### PR TITLE
Add maven wrapper (similar to gradle wrapper)

### PR DESCRIPTION
**Pull request by Shusshu**

### CODE REVIEW

**Comment by TuxPaper** [comment]
Can I assume this is still good for a general BiglyBT-core.jar (aka BiglyBT.jar), and https://github.com/BiglySoftware/BiglyBT-Android/issues/17 would get a new one (say, `BiglyBT-android-core.jar`)?

**Comment by Shusshu** [comment]
Yes but this PR isn't directly related to that.

This allows anyone to build the project using maven without the need to setup anything as it will download the correct version of maven for the user.
Which in turn allow jitpack to build this project for us and store the artifact on their repository

**Comment by Shusshu** [comment]
This can still go in no?

**Comment by TuxPaper** [comment]
Yes, sorry, I thought I clicked the merge button back 6 days ago :/

**Pull request merged**
