### PR TITLE
Update version to the next dev iteration 

### PR DESCRIPTION
**Pull request by Shusshu**
Normally there is a release 1.4.0.0 and then a new dev version but it doesn't really matter I guess...

### CODE REVIEW

**Comment by davisjackie321** [comment]
Yo

**Comment by davisjackie321** [comment]
Yo

**Comment by TuxPaper** [comment]
davisjackie321, you are way too hyper.  Calm down :)

**Comment by davisjackie321** [comment]
Yea

**Comment by davisjackie321** [comment]
Idk what the fuck I’m doing

**Comment by davisjackie321** [comment]
Ya

**Pull request merged**
